post comp fixes
Spikes-2212-Programming-Guild/Crescendo2024 pull request #16
Opened 2024-09-02 11:30 UTC by Spikes-2212

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant requested changes

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on .pathplanner/settings.json
> +}
blank line

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/OI.java
> +
necessary blank line?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/OI.java
> +public class OI /*GEVALD*/ {
multiple magic numbers

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +    int foodAnimation = 0;
are these ever used?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +    int foodAnimation = 0;
if they are, visibility modifier

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +    private SendableChooser<Command> autoChooser = new SendableChooser<>();
final

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +    SpikesLogger logger = new SpikesLogger("Robot");
visibility

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +    LEDService led = LEDService.getInstance();
visibility

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +        root.putCommand("shoot test", new Shoot(Shooter.getInstance(), Drivetrain.getInstance(), ShooterAdjuster.getInstance(),
split to functions

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/Robot.java
> +        root.putCommand("2", new PathPlannerAuto("2"));
i can't remember what this does

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Adjust.java
> +    public RootNamespace namespace = new RootNamespace("why");
final, also namespace name is odd

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/DriveSwerve.java
>      private final SlewRateLimiter xLimiter;
are these used?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/IntakeFromFeeder.java
> +public class IntakeFromFeeder extends ParallelCommandGroup {
was this ever used?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/IntakeNote.java
> +//        if (!storage.seesNote() && moveIntakeAutomatically) {
decide what you want to do with this

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/IntakeNote.java
> +        ledService.attemptIntake();
what does this do? and are you sure it should be in the constructor's outer scope instead of add commands?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/IntakeNote.java
> +                    new MoveGenericSubsystem(intakeRoller, ROLLER_SPEED)
I'll trust you that this ends somehow

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/IntakeNote.java
> +//            addCommands(nezw MoveGenericSubsystem(intakeRoller, 0.5)
decide what you want to do with this

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/OpenIntake.java
> +        addCommands(new MoveSmartMotorControllerGenericSubsystem(intakePlacer, new PIDSettings(0, 0, 10000),
you might want to add inifinite pid settings to spikeslib

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +        feedForwardController.setkS(0);
maybe you should add to spikeslib a FeedForwardController constructor that accepts a Function<FeedForwardSettings, Double> of the calculate method

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +    private static final Pose2d SPEAKER_POSE = new Pose2d(0, 0, new Rotation2d());
perhaps delete

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +    private static final SpikesLogger LOGGER = new SpikesLogger();
maybe you can add to spikeslib `SpikesLogger.getDefaultInstance( )`

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +//    private final Drivetrain drivetrain;
decide

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +                speakerPose = new Pose2d(0.52, 5.59, new Rotation2d());
you have this as a constant

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +    public Shoot(Shooter shooter, Drivetrain drivetrain, ShooterAdjuster adjuster, Storage storage, double height) {
If you want to, you can separate this into functions

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +        return () -> 3900.0;
magic

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Shoot.java
> +        return () -> 3900.0;
ditto

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +    public static final RootNamespace ROOT = new RootNamespace("shoot2");
bad name

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +    private static final Pose2d SPEAKER_POSE = new Pose2d(0, 0, new Rotation2d());
is this used?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +//        Pose2d pose = drivetrain.getPose();
decide

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +                                                300, requiredLeftSpeed.get()) &&
https://www.smogon.com/dex/sv/abilities/magician/

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +                                                300, requiredRightSpeed.get())),
ditto

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +    public ShootWithParameters(Shooter shooter, Drivetrain drivetrain, ShooterAdjuster adjuster, Storage storage,
perhaps separate to functions

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/auto/PathPlannerTest.java
> +public class PathPlannerTest extends FollowPathCommand {
do you want to keep this class in master?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/services/poseestimation/PoseEstimationCameras.java
> +//        PhotonCameraEstimator centerEstimator = new PhotonCameraEstimator(CENTER_CAMERA_NAME, CENTER_CAMERA_LOCATION);
this is sad

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/services/poseestimation/PoseEstimationCameras.java
> +    private SpikesLogger logger = new SpikesLogger();
final

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
>      private Drivetrain(SwerveModule frontLeft, SwerveModule frontRight, SwerveModule backLeft,
perhaps split to functions

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/IntakeRoller.java
> +        namespace.putCommand("move", new MoveGenericSubsystem(this, 0.65));
magic number

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Shooter.java
> + * A class which controls the shooter's speed using 2 {@link ShooterFlywheel}s; one on each side.
not an appropriate use-case for a semicolon

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public Shooter() {
wshould get the instances in the constructor (Dependency Inversion Principle)

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Shooter.java
> +        leftFlywheel.finish();
what's the difference between their stop and finish?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +        master.getPIDController().setOutputRange(-0.7, 0.7);
magic numbers

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    public void periodic() {
??

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +        // @TODO figure out what the fuck
have you figured out what the fuck?

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +}
blank line

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/util/LEDService.java
> +        new Thread(() -> {
explain please

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/util/LEDService.java
> +        for (int i = 0; i < NUMBER_OF_LEDS / 2; i++) {
i trust you that these numbers mean something

2024-09-18 07:26 UTC, Yoel-Perman-Brilliant commented on vendordeps/URCL.json
> +}
blank line

2024-09-19 09:23 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/DriveSwerve.java
>      private final SlewRateLimiter xLimiter;
no, but i believe these should stay as a reference for limiting acceleration (the code they were used in is comment)

2024-09-19 09:34 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/IntakeNote.java
> +        ledService.attemptIntake();
animation which the led displays when you attempt to intake a note

2024-09-19 09:44 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/OpenIntake.java
> +        addCommands(new MoveSmartMotorControllerGenericSubsystem(intakePlacer, new PIDSettings(0, 0, 10000),
sounds good

2024-09-19 09:51 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +        feedForwardController.setkS(0);
you need the setpoint as a parameter

2024-09-20 13:07 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/auto/PathPlannerTest.java
> +public class PathPlannerTest extends FollowPathCommand {
good idea imo to show as a base, besides we dont have another class which represents a pathplanner auto

2024-09-20 13:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/util/LEDService.java
> +        new Thread(() -> {
runs the LEDs on a different thread to not interrupt the robot code (this does not break anything if you are wondering)

2024-09-20 14:13 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +    public ShootWithParameters(Shooter shooter, Drivetrain drivetrain, ShooterAdjuster adjuster, Storage storage,
i dont think theres an easy or efficient way to do that

2024-09-20 14:14 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    public Shoot(Shooter shooter, Drivetrain drivetrain, ShooterAdjuster adjuster, Storage storage, double height) {
again, i dont see an efficient way to do this

2024-10-01 10:53 UTC, TurtleMinecraft requested changes

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/autos/double middle.auto
> +}
blank line

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/autos/single long side.auto
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/autos/single middle.auto
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/autos/single short.auto
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/navgrid.json
> +{"field_size":{"x":16.54,"y":8.21},"nodeSizeMeters":0.3,"grid":[[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/paths/2-1.path
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/paths/2-2.path
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/paths/escpae from long.path
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/deploy/pathplanner/paths/espace from short.path
> +}
ditto

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/OI.java
> +        xbox.getUpButton().onTrue(new CloseIntake(intakePlacer));
for consistency, add a comment for each button

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/Robot.java
> +
delete

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/Robot.java
delete

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/Robot.java
> +
delete

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/Robot.java
> +        // @TODO find out what this does
okay i think i know what this is

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/IntakeNote.java
> +    public static final Supplier<Double> SHOOTER_HEIGHT = () -> 8.0;
put above private constants

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
>  public class Shoot extends ParallelDeadlineGroup {
ordering

2024-10-01 10:53 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/ShootWithParameters.java
> +    public static final RootNamespace ROOT = new RootNamespace("shoot with parameters");
ordering

2024-10-19 23:30 UTC, TurtleMinecraft approved these changes

2024-10-19 23:33 UTC, merged