initial commit
Spikes-2212-Programming-Guild/Crescendo2024 pull request #5
Opened 2024-01-19 11:01 UTC by Yoel-Perman-Brilliant

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/DriveSwerve.java
> +    public boolean isFinished() {
remove

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public static final double MAX_SPEED_METERS_PER_SECONDS = 4;
should check

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public static final double MIN_SPEED_METERS_PER_SECONDS = 0.2;
ditto

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
Everything here about pose estimation is very messy, I HIGHLY recommend seeing trigon's code and adapting it. It's a little complicated at first, but it's a lot more clean and easily allows for multiple cameras

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +//        poseEstimator.resetPosition(
also

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +        driveEncoder.setPositionConversionFactor((1 / DRIVING_GEAR_RATIO) * WHEEL_CIRCUMFERENCE_METERS);
move this to `configureDriveEncoder`

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +                ((1 / DRIVING_GEAR_RATIO) * WHEEL_CIRCUMFERENCE_METERS) / 60);
![image](https://github.com/Spikes-2212-Programming-Guild/Crescendo2024/assets/87820740/c057e627-ab49-42db-b0d1-2c8718c7d46b)

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +        turnEncoder.setPositionConversionFactor((1 / STEERING_GEAR_RATIO) * 360);
![image](https://github.com/Spikes-2212-Programming-Guild/Crescendo2024/assets/87820740/2f932ba4-8fb4-40ac-b0df-8108fa055107)

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +            driveFeedForwardController.setGains(driveFeedForwardSettings.getkS(), driveFeedForwardSettings.getkV(),
there should be the option to just give it the settings

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +     * Takes the module's angle and the desired angle, and returns it in within the range of 0 to 360.
not what it does

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +}
![image](https://github.com/Spikes-2212-Programming-Guild/Crescendo2024/assets/87820740/08f365e7-4538-41f7-a12f-d9845bc58af4)

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModuleHolder.java
> +    private static final RootNamespace namespace = new RootNamespace("swerve module holder 2");
2?

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModuleHolder.java
> +            new PIDSettings(0, 0, 0, 0, 0));
change everything to -1 so it crashes

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModuleHolder.java
> +            new FeedForwardSettings(0, 0, 0, 0));
ditto

2024-01-22 11:19 UTC, Yoel-Perman-Brilliant commented on vendordeps/Phoenix6.json
> +}
![image](https://github.com/Spikes-2212-Programming-Guild/Crescendo2024/assets/87820740/96b27a02-c33b-4aa4-9a38-127a8161d392)

2024-01-26 07:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/DriveSwerve.java
> +        this.xLimiter = new SlewRateLimiter(DRIVE_ACCELERATION_LIMIT_PERCENTAGE);
remove percentage

2024-01-26 07:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public void pain() {
remove

2024-01-26 07:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        namespace.putRunnable("move PLEWA,SP;RKW.OIA", this::pain);
remove

2024-01-26 07:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +            driveController.getPIDController().setReference(speed, CANSparkMax.ControlType.kVelocity, PID_SLOT,
make sure the feed forward is in voltages

2024-01-26 07:53 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +     * in appropriate scope for CTRE onboard control.
Rev not ctre

2024-01-26 09:52 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/DriveSwerve.java
> +    private static final double TURN_ACCELERATION_LIMIT_PERCENTAGE = 4;
no PRECENTAGE

2024-01-27 08:20 UTC, nettahalamish commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
delete

2024-01-27 08:47 UTC, nettahalamish commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +     * Credit to team #364
.

2024-01-27 09:04 UTC, nettahalamish requested changes

2024-01-27 09:04 UTC, nettahalamish commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +     * Credit to team #364
.

2024-01-27 09:04 UTC, nettahalamish commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
delete

2024-01-29 19:11 UTC, Spikes-2212 requested changes

2024-01-29 19:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +    private void configureAbsoluteEncoder() {
that's not a thing that's going to work

2024-01-29 19:17 UTC, Spikes-2212 approved these changes

2024-01-30 15:11 UTC, Spikes-2212 requested changes

2024-01-30 15:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public final SwerveModule frontLeft;
make all modules private

2024-01-30 15:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +    public final CANSparkMax driveController;
private both motors

2024-01-30 15:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +        turnController.setPeriodicFramePeriod(CANSparkLowLevel.PeriodicFrame.kStatus2, 40);
![image](https://github.com/Spikes-2212-Programming-Guild/Crescendo2024/assets/4534093/29314a9f-f219-4eb4-a2d5-4848808abccd)

2024-01-30 15:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +        turnController.setIdleMode(CANSparkMax.IdleMode.kCoast);
bro why turn it coast twice

2024-01-30 15:11 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +    public void configFF() {
put above private methods

2024-01-30 15:23 UTC, Spikes-2212 approved these changes

2024-01-31 16:58 UTC, TurtleMinecraft approved these changes

2024-02-01 15:30 UTC, merged