Yorai shoot
Spikes-2212-Programming-Guild/Crescendo2024 pull request #6
Opened 2024-01-19 12:58 UTC by yo12344444444444

2024-01-27 16:15 UTC, TurtleMinecraft requested changes

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    /**
unrelated docs

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected final PIDSettings leftPIDSettings;
why protected?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +     * The PID Settings for the PID loop operating on the right side of the drivetrain.
drivetrain? isnt this a command for adjusting a shooter?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected final PIDSettings leftPIDSettings;
theres only 1 motor on the adjuster, no need for left and right PID

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected final PIDSettings rightPIDSettings;
why protected?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected final FeedForwardSettings leftFeedForwardSettings;
why protected?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +     * The FeedForwards Settings of the FeedForward loop operating on the left side of the drivetrain.
not a drivetrain and only 1 FF is needed

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +     * The FeedForwards Settings of the FeedForward loop operating on the right side of the drivetrain.
ditto

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected final FeedForwardSettings rightFeedForwardSettings;
why protected?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    private final CANSparkBase master;
first of all, we are using spark maxes, no reason to use spark base.
and more importantly, this is a command. why does it have a motor as a field?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected Supplier<Double> leftSetpoint;
why protected? also only 1 setpoint is needed

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +    protected Supplier<Double> leftSource;
ditto

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +     * How far the left side of the drivetrain drove.
not. a. drivetrain.

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/AdjustShooter.java
> +public class AdjustShooter extends Command {
extend movesmartmotorcontrollergenericsubsystem

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/MoveStorage.java
> +public class MoveStorage extends Command {
why does this class have nothing

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +public class RotateSwerveWithPID extends Command {
classes should start with a blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +    public RotateSwerveWithPID(Drivetrain drivetrain, Supplier<Double> sours, Supplier<Double> setpoint, PIDSettings pidSettings, FeedForwardSettings feedForwardSettings){
source*

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +
remove this space

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +    public RotateSwerveWithPID(Supplier<Double> source ,Supplier<Double> setPoint ){
ctrl alt l + setpoint is 1 word

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +
remove line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/RotateSwerveWithPID.java
> +
remove line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    private final GetFunk getFunk;
?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +public class Shoot extends ParallelCommandGroup {
classes should start with a blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    public Shoot(frc.robot.subsystems.ShooterAdjuster shooterAdjuster, Drivetrain drivetrain, Storage storage,
import the class instead of saying frc.robot.subsystems.ShooterAdjuster

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +                new RotateSwerveWithPID(drivetrain, drivetrain::rotation, this::getRequireRobotAngle,
ctrl alt l please

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    public double getRequireShooterAngle(int x, int y) {
required*

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    public double getRequireRobotAngle() {
required*

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/Shoot.java
> +    public double getSpeed() {
speed of what?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +    /**
delete these docs

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +public class SpeedUpShooter extends Command {
im assuming that this class makes the shooter move, in that case it should extend parallelcommandgroup as we want to control both flywheels at different speeds using movesmartmotorcontrollergenericsubsystem

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +    SparkGenericSubsystem leftMotor;
1. where visibility
2. just use the subsystem Shooter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +    public void stop(){
ctrl alt l

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +
remove line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
remove line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +public class Drivetrain extends DashboardedSubsystem {
classes should begin with a blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings pidSettings(){
ctrl alt l

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        return pose;
return new Pose2d();

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public double rotation(){
getRotation

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    // using mcs
mcs?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/GetFunk.java
> +        GetFunk(double i, double i1) {
i? i1?

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/GetFunk.java
> +        pose1(1.0,3.0),
ctrl alt l

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +public abstract class Shooter{
ctrl alt l also classes start with a blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public final CANSparkBase leftMotor;
why sparkbase we use sparkmax

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public PIDSettings leftPidSettings(){
getLeftPIDSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public PIDSettings rightPidSettings(){
getRightPIDSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public FeedForwardSettings leftFeedForwardSettings(){
getLeftFeedForwardSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public FeedForwardSettings rightForwardSettings(){
getRightFeedForwardSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +
remove random line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Shooter.java
> +
remove random line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    public PIDSettings pidSettings(){
getPIDSettings also ctrl alt l

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    }
enter

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    public FeedForwardSettings feedForwardSettings(){
getFeedForwardSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    public TrapezoidProfileSettings trapezoidProfileSettings(){
getTrapezoidProfileSettings

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    /**
unrelated docs

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +
remove blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +    public ShooterAdjuster(String namespaceName, CANSparkBase master, CANSparkBase... slaves) {
slaves? theres 1 motor

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/ShooterAdjuster.java
> +
remove line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Storage.java
> +public class Storage extends SparkGenericSubsystem {
classes begin with a blank line

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Storage.java
> +    /**
unrelated docs

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Storage.java
> +    public Storage(String namespaceName, CANSparkBase master, CANSparkBase... slaves) {
only 1 motor

2024-01-27 16:15 UTC, TurtleMinecraft commented on src/main/java/frc/robot/subsystems/Storage.java
> +
remove blank line

2024-01-31 15:12 UTC, Spikes-2212 requested changes

2024-01-31 15:12 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Shooter.java
> +
remove blank line

2024-01-31 15:12 UTC, Spikes-2212 commented on src/main/java/frc/robot/commands/SpeedUpShooter.java
> +
remove blank line

2024-01-31 15:15 UTC, Spikes-2212 approved these changes

2024-01-31 16:58 UTC, TurtleMinecraft approved these changes

2024-01-31 16:59 UTC, merged